from .support_command import PiecesSupportCommand
from .reload_command import PiecesReloadCommand
from .open_pieces_command import PiecesOpenPiecesCommand
from .about_command import PiecesOpenNotesCommand,PiecesAboutCommand
from .onboarding_command import PiecesOnboardingCommand,PiecesOnboardingCommandsCommand,PiecesResetOnboardingCommand
from .close_command import PiecesCloseOsCommand
from .install_pieces_os import PiecesInstallPiecesOsCommand