name: Update Sublime Dependencies

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone and install vendoring tool
        run: |
          git clone https://github.com/pradyunsg/vendoring.git vendoring-tool
          cd vendoring-tool
          pip install .

      - name: Clone plugin_sublime_dependencies and run vendoring sync
        run: |
          git clone https://github.com/pieces-app/plugin_sublime_dependencies.git sublime-deps
          cd sublime-deps
          vendoring sync
          # Remove old _pieces_lib if it exists
          if [ -d "../_pieces_lib" ]; then
            rm -rf ../_pieces_lib
            echo "Removed old _pieces_lib directory"
          fi
          # Copy the newly generated _pieces_lib to our repository
          cp -r _pieces_lib ../

      - name: Remove directories containing semver or dist # We no longer use semver or dist in _pieces_lib
        run: |
          if [ -d "_pieces_lib" ]; then
            # Find and remove all directories containing 'semver' or 'dist' in their name (only direct children of _pieces_lib)
            found_semver=$(find _pieces_lib -maxdepth 1 -type d -name '*semver*' 2>/dev/null)
            found_dist=$(find _pieces_lib -maxdepth 1 -name '*dist*' 2>/dev/null)
            
            if [ -n "$found_semver" ]; then
              echo "Found directories containing 'semver':"
              echo "$found_semver"
              find _pieces_lib -maxdepth 1 -type d -name '*semver*' -exec rm -rf {} +
              echo "Removed all directories containing 'semver' from _pieces_lib"
            else
              echo "No directories containing 'semver' found in _pieces_lib"
            fi
            
            if [ -n "$found_dist" ]; then
              echo "Found files/directories containing 'dist':"
              echo "$found_dist"
              find _pieces_lib -maxdepth 1 -name '*dist*' -exec rm -rf {} +
              echo "Removed all files/directories containing 'dist' from _pieces_lib"
            else
              echo "No files/directories containing 'dist' found in _pieces_lib"
            fi
          else
            echo "_pieces_lib directory does not exist yet"
          fi

      - name: Clean up temporary directories
        run: |
          rm -rf vendoring-tool sublime-deps
          echo "Cleaned up temporary directories"

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update _pieces_lib dependencies"
          title: "Update sdks"
          body: |
            update sdks

            Auto-generated by the Update Sublime Dependencies workflow.
          branch: update-pieces-lib-${{ github.run_number }}
          base: main
          reviewers: bishoy-at-pieces
